SASS-3297 - Implemented OverseasTransferChargePaidController
hmrc/income-tax-pensions-frontend pull request #165
Opened 2023-01-30 14:57 UTC by abiodxn

# Checklist

Jira subtask: SASS-____

## Developer: Before Asking Others To Review Your Code

Have you ...

- [ ]  Had a QA verify that all acceptance criteria have been met, with comment(s) in the ticket? 
- [ ]  Hosted a group review of your implementation?
- [ ]  Rebased against `main`? 
- [ ]  Ensured that your commit(s) contain the ticket key?
- [ ]  Ensured that your branch is named after the ticket key?
- [ ]  Successfully run the unit tests?
- [ ]  Successfully run the integration tests?
- [ ]  Successfully run the journey tests? If not, please add a comment explaining why it wasn't necessary.
- [ ]  Ensured that the PR job has passed.

## Reviewer: Before Reviewing

Have you ...

- [ ]  Pulled the branch down?
- [ ]  Assigned yourself to this PR?
- [ ]  Moved the Jira *subtask* to “in review”?

## Developer: After Approval

Have you ...

- [ ]  Moved the Jira *subtask* to “in pipeline”?

## Developer: After Merging

Have you ...

- [ ]  Scheduled a demo? If not, please add a comment.

2023-01-30 18:20 UTC, edem-nsefik-hmrc requested changes

2023-01-30 18:20 UTC, edem-nsefik-hmrc commented on app/controllers/pensions/transferIntoOverseasPensions/OverseasTransferChargePaidController.scala
> +      controllers.pensions.transferIntoOverseasPensions.routes.OverseasTransferChargePaidController.show(taxYear, pensionSchemeIndex) //Redirect to
When creating adding a new Pension scheme pensionSchemeIndex = None but the size of pensionSchemeLists has increased. How will the next page know which pension scheme has been added with the UKCharge question in order to set the remaining pension scheme values

2023-01-31 09:29 UTC, adam-shahzad-2 requested changes

2023-01-31 14:15 UTC, adam-shahzad-2 approved these changes

2023-01-31 14:31 UTC, edem-nsefik-hmrc approved these changes

2023-01-31 14:58 UTC, merged