[SASS-3726] Create Page: 'When did you get your state pension lump sum'
hmrc/income-tax-pensions-frontend pull request #223
Opened 2023-04-14 13:50 UTC by Jake-Raffe

# Checklist

Jira subtask: SASS-____

## Developer: Before Asking Others To Review Your Code

Have you ...

- [ ]  Had a QA verify that all acceptance criteria have been met, with comment(s) in the ticket? 
- [ ]  Hosted a group review of your implementation?
- [ ]  Rebased against `main`? 
- [ ]  Ensured that your commit(s) contain the ticket key?
- [ ]  Ensured that your branch is named after the ticket key?
- [ ]  Successfully run the unit tests?
- [ ]  Successfully run the integration tests?
- [ ]  Successfully run the journey tests? If not, please add a comment explaining why it wasn't necessary.
- [ ]  Ensured that the PR job has passed.

## Reviewer: Before Reviewing

Have you ...

- [ ]  Pulled the branch down?
- [ ]  Assigned yourself to this PR?
- [ ]  Moved the Jira *subtask* to “in review”?

## Developer: After Approval

Have you ...

- [ ]  Moved the Jira *subtask* to “in pipeline”?

## Developer: After Merging

Have you ...

- [ ]  Scheduled a demo? If not, please add a comment.

2023-04-14 17:15 UTC, edem-nsefik-hmrc requested changes

2023-04-17 07:46 UTC, adam-shahzad-2 commented on it/controllers/pensions/incomeFromPensions/StatePensionLumpSumStartDateControllerISpec.scala
> +      inputFieldValueCheck(dayInputName, Selectors.dayInputSelector, "")
there needs to be some error handling tests in the IT specs, as the date forms validation happens in the controller, and not the view

2023-04-17 08:27 UTC, adam-shahzad-2 commented on test/views/pensions/incomeFromPensions/StatePensionLumpSumStartDateViewSpec.scala
> +    val emptyYearErrorText: String
Get rid of this if you are not using it

2023-04-17 10:11 UTC, edem-nsefik-hmrc approved these changes

2023-04-17 10:15 UTC, merged