[SASS-3785] Single Amount Is Not Pre-populated On Page: 'Your pension lump sum'
hmrc/income-tax-pensions-frontend pull request #225
Opened 2023-04-17 10:53 UTC by adam-shahzad-2

# Checklist

Jira subtask: [SASS-3785](https://jira.tools.tax.service.gov.uk/browse/SASS-3785)

## Developer: Before Asking Others To Review Your Code

Have you ...

- [ ]  Had a QA verify that all acceptance criteria have been met, with comment(s) in the ticket? 
- [ ]  Hosted a group review of your implementation?
- [ ]  Rebased against `main`? 
- [ ]  Ensured that your commit(s) contain the ticket key?
- [ ]  Ensured that your branch is named after the ticket key?
- [ ]  Successfully run the unit tests?
- [ ]  Successfully run the integration tests?
- [ ]  Successfully run the journey tests? If not, please add a comment explaining why it wasn't necessary.
- [ ]  Ensured that the PR job has passed.

## Reviewer: Before Reviewing

Have you ...

- [ ]  Pulled the branch down?
- [ ]  Assigned yourself to this PR?
- [ ]  Moved the Jira *subtask* to “in review”?

## Developer: After Approval

Have you ...

- [ ]  Moved the Jira *subtask* to “in pipeline”?

## Developer: After Merging

Have you ...

- [ ]  Scheduled a demo? If not, please add a comment.

2023-04-17 12:19 UTC, edem-nsefik-hmrc requested changes

2023-04-17 12:19 UTC, edem-nsefik-hmrc commented on app/controllers/pensions/lifetimeAllowances/PensionLumpSumDetailsController.scala
>    def show(taxYear: Int): Action[AnyContent] = (authAction andThen taxYearAction(taxYear)).async { implicit request =>
Any reason not to upgrade to use actionProvider here and to replace getPensionsSessionDataResult with getPensionSessionData

2023-04-17 12:19 UTC, edem-nsefik-hmrc commented on it/controllers/pensions/lifetimeAllowances/PensionLumpSumDetailsControllerISpec.scala
> +          titleCheck(user.specificExpectedResults.get.expectedTitle, user.isWelsh)
This common parts of this block should be put in a method and called here and in the test following

2023-04-18 11:37 UTC, edem-nsefik-hmrc approved these changes

2023-04-18 13:19 UTC, Jake-Raffe approved these changes

2023-04-18 15:34 UTC, merged