SASS-2582 overseas payments
hmrc/income-tax-pensions-frontend pull request #98
Opened 2022-08-09 14:12 UTC by walesoares

### Description
payment into overseas page 

Add a link to the relevant story in Jira
[SASS-2582](https://jira.tools.tax.service.gov.uk/browse/SASS-2582)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-08-10 12:05 UTC, srinivaspach requested changes

2022-08-10 12:05 UTC, srinivaspach commented on it/controllers/pensions/paymentsIntoOverseasPensions/PaymentIntoPensionSchemeControllerISpec.scala
> +
We do not have a test case for user selecting No and an amount is already there. Let's say the page get's populated with Yes and an amount. But user selects No and then hits the Submit button.

2022-08-11 09:49 UTC, srinivaspach approved these changes
Looks good to me

2022-08-11 14:38 UTC, erasmos-hmrc commented
This was rebased after @srinivaspach, but there were no significant changes so I think it's safe to re-approve.

2022-08-11 14:39 UTC, srinivaspach approved these changes

2022-08-11 14:39 UTC, merged