SASS 3251 - Update Pension Income
hmrc/income-tax-pensions-frontend pull request #99
Opened 2022-08-11 10:05 UTC by abiodxn

### Description
Please include a brief summary of the change you've made and the issue that it fixes.

Add a link to the relevant story in Jira
[SASS-3248](https://jira.tools.tax.service.gov.uk/browse/SASS-3248)

### Checklist PR Reviewer
##### Before Reviewing
- [ ]  Have you pulled the branch down?
- [ ]  Have you assigned yourself to the PR?
- [ ]  Have you moved the task to “in review” on JIRA?
- [ ]  Have you checked to ensure all dependencies are up to date?
- [ ]  Have you checked to ensure its been rebased against the current version of main?

##### Whilst Reviewing
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests?
- [ ]  Have you looked at the JIRA story to make sure all Acceptance Criteria has been met?

##### After Reviewing
- [ ]  Have you checked for merge conflicts or any changes in the current main that may affect the current pull request? i.e. does it need another rebase?
- [ ]  Have you checked to make sure there are no builds in the pipeline before you merge?
- [ ]  Have you moved the task to “in pipeline” on Jira?

### Checklist PR Raiser
##### Before creating PR
- [ ]  Have you run the tests?
- [ ]  Have you run the journey tests? (where applicable)
- [ ]  Have you addressed warnings where appropriate?
- [ ]  Have you rebased against the current version of main?
- [ ]  Have you checked code coverage isn’t lower than previously?

##### After PRs been raised
- [ ]  Have you checked the PR Builder passes?

2022-09-06 07:51 UTC, erasmos-hmrc commented
@abiodxn , could you amend the commit message to contain the parent key (SASS-3248)?

2022-09-06 13:59 UTC, salman-a-dev approved these changes

2022-09-20 14:12 UTC, srinivaspach requested changes
Looks good to me

2022-09-20 14:12 UTC, srinivaspach commented on test/builders/PaymentsIntoOverseasPensionsViewModelBuilder.scala
>      doubleTaxationCountryCode = None,
Any reason why these are left as None?

2022-09-20 14:22 UTC, erasmos-hmrc commented on app/models/pension/AllPensionsData.scala
> +    paymentsIntoOverseasPensions = PaymentsIntoOverseasPensionsViewModel(
As mentioned during group review, there's much duplication.

The alternative I had in mind was something like this:

```
private def paymentsIntoOverseasPensionsViewModel(prior: AllPensionsData): PaymentsIntoOverseasPensionsViewModel = (prior.pensionIncome, prior.pensionReliefs) match {
    case (Some(pensionsIncome), Some(pensionsReliefs)) => paymentsIntoOverseasPensionsViewModel(pensionsIncome, pensionsReliefs.pensionReliefs)
    case (Some(pensionsIncome), None) => paymentsIntoOverseasPensionsViewModel(pensionsIncome)
    case (None, Some(pensionsReliefs)) => paymentsIntoOverseasPensionsViewModel(pensionsReliefs.pensionReliefs)
    case (None, None) => paymentsIntoOverseasPensionsViewModel()
  }
```

However, given the limited time, best to leave it like this.

2022-09-20 14:28 UTC, srinivaspach approved these changes
Looks good to me

2022-09-20 14:35 UTC, srinivaspach approved these changes

2022-09-20 14:45 UTC, merged